### ISSUE TITLE
Installing a new Ruby version without bundler version preference can lead to incompatible bundler/rubygems setup

### ISSUE THREAD

**Issue by foobear** [makandra/capistrano-opscomplete#10]
On a project with "unmanaged" Ruby, I upgraded my `.ruby-version` and started deploying. The new Ruby version was installed successfully, and capistrano-opscomplete installed Geordi afterwards, but did not try to install the most recent version of Bundler.

I don't use `set :bundler_version` as any version should be fine. My `Gemfile.lock` was bundled with Bundler 2.0.1.

I am not sure if the issue is with Rubygems 3.0.3 being incompatible with Bundler < 2, or if Bundler < 2 always fails when it encounters a lock file for Bundler 2.0.1.

If possible, I'd like to avoid forcing a specific bundler version. Can we maybe have a way to define a minimum required bundler version?
Or, if it's a compatibility issue between Rubygems and Bundler, upgrade to the latest Bundler version once, after installing a new Ruby.

**Comment by makrobin** [comment]
As described in #12 we now quote the version string when passing it to the shell. This allows defining a "minimum required bundler version" with a version string linke '~>2'. Will be included in 0.4.0
