### ISSUE TITLE
Quote value from `set :bundler_version` for `gem install`

### ISSUE THREAD

**Issue by foobear** [makandra/capistrano-opscomplete#12]
When using `set :bundler_version, '~> 2.0.2'`, installing the gem fails because the version value is not quoted:

```
rbenv exec gem install bundler --no-document --version ~> 2.0.2
```

I believe this should generally be quoted just because it's passed to a shell command.

```
rbenv exec gem install bundler --no-document --version '~> 2.0.2'
```

Bonus benefit would be support for values such as the above.

**Comment by makrobin** [comment]
Thanks for reporting. This will be fixed in version 0.4.0.
