### ISSUE TITLE
Remove or namespace deploy:revision task

### ISSUE THREAD

**Issue by foobear** [makandra/capistrano-opscomplete#18]
This gem includes a `deploy:revision` task.

The task itself is useful, but not really bound to the OpsComplete setup and should be removed, or at the very least live inside the `opscomplete` namespace.

Either way is fine with me.

**Comment by ghost** [comment]
Fixed in 0.6.2 (https://github.com/makandra/capistrano-opscomplete/commit/3b6ea6affaf9d2f9d3e7b26cc05e280b2cbc1165)
