### ISSUE TITLE
`opscomplete:supervisor:gen_config` does not use the app's Ruby & gem versions

### ISSUE THREAD

**Issue by makmic** [makandra/capistrano-opscomplete#38]
During the first deployment of a new application I ran into this issue (boiled down capistrano output):

```plain
00:07 opscomplete:ruby:update_ruby_build
      01 ruby_update_management_tool update_build
      01 Updating ruby-build
      WARN  Could not look up installed versions. This is probably the first ruby install.
      Configured Ruby version is not installed, but available for installation.
      02 ruby_install_version '3.3.5'
      02 ==> Installed ruby-3.3.5 to /home/MY_USER/.rbenv/versions/3.3.5
      02 3.3 => 3.3.5
      02
      02 NOTE:
      02  to activate this Ruby version as the new default, run: rbenv global 3.3.5
      02
      03 ruby_set_version '3.3.5'
08:45 opscomplete:ruby:rehash
      01 ruby_update_management_tool rehash
09:00 opscomplete:supervisor:gen_config
      01 supervisor_gen_config 
      01 /var/lib/gems/3.2.0/gems/foreman-0.85.0/lib/foreman/export/base.rb:86:in `rescue in chown': undefined method…
      01
      01     error("Could not chown #{dir} to #{user}") unless File.writable?(dir) || ! File.exists?(dir)
      01                                                                                    ^^^^^^^^
      01 Did you mean?  exist?
      01 	from /var/lib/gems/3.2.0/gems/foreman-0.85.0/lib/foreman/export/base.rb:83:in `chown'
```

The project's `.ruby-version` stated 3.3.5, which is why `opscomplete:ruby:update_ruby_build` had to install.
The `opscomplete:supervisor:gen_config` task however seems to be executed with the Ruby version of `rbenv shell system`, which is 3.2 on the server. 

Secondly, the `supervisor_gen_config` command seems to use a different set of gem versions than those specified in my bundle.
While my app ships with `foreman` 0.88.1, the error above refers to 0.85.0. The fix for the the `File.exist?` NoMethodError was [only fixed in 0.88.0](https://github.com/ddollar/foreman/blob/main/Changelog.md#0880-2024-04-12).

I'm not sure about the best way forward, but we can team up on solving this issue if you want.

**Comment by kj-makandra** [comment]
This issue is not in capistrano-opscomplete. This was an issue in our infrastructure and got fixed there.
