### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by judithroth** [makandra/capistrano-opscomplete#7]
I am not sure if you are already aware of this. With capistrano-opscomplete 0.2.0 and capistrano 3.11.0 there is the following deprecation warning when deploying:

```
Capistrano tasks may only be invoked once. Since task `opscomplete:ruby:update_ruby_build' was previously invoked, invoke("opscomplete:ruby:update_ruby_build") at /home/judith/.rbenv/versions/2.5.5/lib/ruby/gems/2.5.0/gems/capistrano-opscomplete-0.2.0/lib/capistrano/opscomplete/tasks.rake:79 will be skipped.
If you really meant to run this task again, use invoke!("opscomplete:ruby:update_ruby_build")
THIS BEHAVIOR MAY CHANGE IN A FUTURE VERSION OF CAPISTRANO. Please join the conversation here if this affects you.
https://github.com/capistrano/capistrano/issues/1686

```
It's printed in dark red so on first glance I always think my deploy failed :/

**Comment by makrobin** [comment]
Hi @judithroth,

thanks for your feedback! We address this in [31ba8912bd69ca92e7ac024e7846f1a816cfba10](https://github.com/makandra/capistrano-opscomplete/commit/31ba8912bd69ca92e7ac024e7846f1a816cfba10) which is targeted for release 0.3.0.

Cheers!

**Comment by judithroth** [comment]
:+1: :rocket: thanks!

**Comment by makrobin** [comment]
Was included in our latest release: https://rubygems.org/gems/capistrano-opscomplete/versions/0.3.0
